// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyickadmqjjiceroffag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aWNrYWRtcWpqaWNlcm9mZmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzIzMDUsImV4cCI6MjA2ODE0ODMwNX0.AeH7tWXkOA8RISnSj461aBue4G1--9Ji25hpLykuJGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});